# Generated by Django 2.2.4 on 2019-08-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
